
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "cloud-run-1" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "qwiklabs-asl-02-c74cc833bee1"
  location                      = "us-central1"
  service_name                  = "green-odyssey-v3-5e33"
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/qwiklabs-asl-02-c74cc833bee1/ev-trip-planner/green-odyssey:latest", "container_name" = "green-odyssey-v3-container", "ports" = {"container_port" = 8080, "name" = "http1"}, "resources" = {"cpu_idle" = true, "startup_cpu_boost" = false}}]
  gpu_zonal_redundancy_disabled = false
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-qwiklabs-asl-02-c74cc833bee1, module.project-services-billing-project]
}
resource "google_cloud_run_v2_service_iam_member" "public_access" {
  project  = module.cloud-run-1.project_id
  location = module.cloud-run-1.service_location
  name     = module.cloud-run-1.service_name
  role     = "roles/run.invoker"
  member   = "allUsers"
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = "qwiklabs-asl-02-c74cc833bee1"
  location       = "global"
  service_uris   = [module.cloud-run-1.apphub_service_uri]
  application_id = "green-odyssey-v3"
}
module "project-services-qwiklabs-asl-02-c74cc833bee1" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "qwiklabs-asl-02-c74cc833bee1"
  disable_services_on_destroy = false
  activate_apis               = ["cloudresourcemanager.googleapis.com", "compute.googleapis.com", "iam.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "run.googleapis.com", "serviceusage.googleapis.com", "storage-api.googleapis.com"]
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "qwiklabs-asl-02-c74cc833bee1"
  disable_services_on_destroy = false
  activate_apis               = ["apphub.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "iam.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "run.googleapis.com", "serviceusage.googleapis.com", "storage-api.googleapis.com"]
}
